---
site_name: India Investments Wiki
site_url: https://mkdocs.indiainvestments.wiki
repo_url: https://github.com/indiainvestments/wiki
repo_name: indiainvestments/wiki
copyright: >-
  &copy; Licensed Under
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt"
  target="_blank" rel="noopener noreferrer">CC-BY-NC-SA-4.0</a>

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: "#"

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Hindi
      link: /hi/
      lang: hi
